<a href="https://colab.research.google.com/github/MONICA-IT21/MACHINE_LEARNING/blob/main/Day3_Naive_Bayes_Algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.naive_bayes import GaussianNB

In [ ]:
df=pd.read_csv('seattle-weather.csv')
df

            date  precipitation  temp_max  temp_min  wind  weather
0     2012-01-01            0.0      12.8       5.0   4.7  drizzle
1     2012-01-02           10.9      10.6       2.8   4.5     rain
2     2012-01-03            0.8      11.7       7.2   2.3     rain
3     2012-01-04           20.3      12.2       5.6   4.7     rain
4     2012-01-05            1.3       8.9       2.8   6.1     rain
...          ...            ...       ...       ...   ...      ...
1456  2015-12-27            8.6       4.4       1.7   2.9     rain
1457  2015-12-28            1.5       5.0       1.7   1.3     rain
1458  2015-12-29            0.0       7.2       0.6   2.6      fog
1459  2015-12-30            0.0       5.6      -1.0   3.4      sun
1460  2015-12-31            0.0       5.6      -2.1   3.5      sun

[1461 rows x 6 columns]

In [ ]:
Numerics=LabelEncoder()

In [ ]:
inputs=df.drop('wind',axis='columns')
target=df['wind']
target

0       4.7
1       4.5
2       2.3
3       4.7
4       6.1
       ...
1456    2.9
1457    1.3
1458    2.6
1459    3.4
1460    3.5
Name: wind, Length: 1461, dtype: float64

In [ ]:
inputs['outlook_n']=Numerics.fit_transform(inputs['precipitation'])
inputs['Temp_n']=Numerics.fit_transform(inputs['temp_max'])

inputs['windy_n']=Numerics.fit_transform(inputs['weather'])
inputs

,date,precipitation,temp_max,temp_min,weather,outlook_n,Temp_n,windy_n
0,2012-01-01,0.0,12.8,5.0,drizzle,0,25,0
1,2012-01-02,10.9,10.6,2.8,rain,43,21,2
2,2012-01-03,0.8,11.7,7.2,rain,3,23,2
3,2012-01-04,20.3,12.2,5.6,rain,74,24,2
4,2012-01-05,1.3,8.9,2.8,rain,5,18,2
...,...,...,...,...,...,...,...,...
1456,2015-12-27,8.6,4.4,1.7,rain,34,10,2
1457,2015-12-28,1.5,5.0,1.7,rain,6,11,2
1458,2015-12-29,0.0,7.2,0.6,fog,0,15,1
1459,2015-12-30,0.0,5.6,-1.0,sun,0,12,4
1460,2015-12-31,0.0,5.6,-2.1,sun,0,12,4

In [ ]:
inputs_n=inputs.drop(['date','precipitation','temp_max','temp_min','weather'],axis='columns')
inputs_n

      outlook_n  Temp_n  windy_n
0             0      25        0
1            43      21        2
2             3      23        2
3            74      24        2
4             5      18        2
...         ...     ...      ...
1456         34      10        2
1457          6      11        2
1458          0      15        1
1459          0      12        4
1460          0      12        4

[1461 rows x 3 columns]

In [ ]:
inputs['weather']=Numerics.fit_transform(inputs['weather'])